### ISSUE TITLE
Initialization fragment

### ISSUE THREAD

**Issue by DarbyCrash** [bitmovin/MP4Inspector#7]
Hi. I'm trying to analize a smooth streaming live stream in edge using bitmovin drm test player but I cannot retrieve initialization fragment in dev tools's mp4 inspector tab. is there a way for analize builded initialization fragment?

**Comment by bitmovin-kenny** [comment]
Hi @DarbyCrash, the problem with Smooth Streaming is, that there is no initialization segment and that the player has to generate it using information from the manifest and the first data segment. So it will never show up in the downloaded data.

You could use the ["Capture generated data" approach](https://github.com/bitmovin/MP4Inspector#capturing-generated-data) to grab the segment which is pushed into the SourceBuffer.
